version: "3.5"
volumes:
  cache: # Added to support Windows 10 Docker
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - ".:/workspace"
      - cache:/cache # Added to support Windows 10 Docker
    depends_on:
      - mysql
    environment:
      SPROCKETS_CACHE: /cache # Added to support Windows 10 Docker
      RAILS_ENV: development
      DB_USER: root
      DB_NAME: dev
      DB_PASSWORD: root
      DB_HOST: mysql
    ports:
      - "3010:3000"
    links:
      - mysql
